version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  springbootapp:
    image: ji0513ji/game-server:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis

