


spring:
  profiles:
    group:
      "local": "localRedis"
      "prod": "prodRedis, prodPort, secret, web-mvc"
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/webflux
    username: root
    password:
    initialization-mode: always

---

spring:
  config:
    activate:
      on-profile: "localRed"
  data:
    redis:
      host: local
      port: 6379
      password:
      timeout: 5000


---

spring:
  config:
    activate:
      on-profile: "prodRedis"

  data:
    redis:
      host: redis
      port: 6379
      password:
      timeout: 5000
