
spring:
  profiles:
    group:
      "local": "localDB"
      "prod": "prodDB"
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/webflux
    username: root
    password: ${MYSQL_PASSWORD}
    #initialization-mode: always
  data:
    mongodb:
        uri: ${MONGO_URL}

---

spring:
  config:
    activate:
      on-profile: "localDB"

---

spring:
  config:
    activate:
      on-profile: "prodDB"