
spring:
  profiles:
    group:
      "local": "localDB"
      "prod": "prodDB"
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/webflux
    username: root
    password:
    initialization-mode:
  data:
    mongodb:
      uri: mongodb://root:${MONGO_PASSWORD}@localhost:27017/${MONGO_DATABASE}?authSource=admin


---

spring:
  config:
    activate:
      on-profile: "localDB"
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 5000


---

spring:
  config:
    activate:
      on-profile: "prodDB"

  data:
    redis:
      host: redis
      port: 6379
      password:
      timeout: 5000
