


spring:
  profiles:
    group:
      "local": "localDB"
      "prod": "prodDB"
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/webflux
    username: root
    password:
    initialization-mode: always

---

spring:
  config:
    activate:
      on-profile: "localDB"
  data:
    redis:
      host: local
      port: 6379
      password:
      timeout: 5000


---

spring:
  config:
    activate:
      on-profile: "prodDB"

  data:
    redis:
      host: redis
      port: 6379
      password: 12345678
      timeout: 5000
