spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/webflux
    username: root
    password: ${MYSQL_PASSWORD}
  data:
    mongodb:
      uri: ${MONGO_URL}

  config:
    activate:
      on-profile: "default"
  application:
    name: dis-game-service
  cloud:
    config:
      enabled: false  # 로컬 환경에서 Config 서버 비활성화
server:
  port: 9005

eureka:
  client:
    enabled: false  # 로컬 환경에서 Eureka 클라이언트 비활성화


---

spring:
  config:
    activate:
      on-profile: "localDB-9001"
  application:
    name: dis-game-service-1
server:
  port: 9001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: localhost
    instance-id: ${spring.application.name}:${server.port}


---

spring:
  config:
    activate:
      on-profile: "localDB-9002"
  application:
    name: dis-game-service-2
server:
  port: 9002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: localhost
    instance-id: ${spring.application.name}:${server.port}

---

spring:
  config:
    activate:
      on-profile: "localDB-9003"
  application:
    name: dis-game-service-3
server:
  port: 9003

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: localhost
    instance-id: ${spring.application.name}:${server.port}
