version: '3'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: webflux
      MYSQL_ROOT_PASSWORD: 12345678
      TZ: Asia/Seoul
    volumes:
      - ../sql/user:/docker-entrypoint-initdb.d

  springbootapp:
    restart: on-failure
    image: ji0513ji/game-server:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: prodDB
      SPRING_DATA_MONGODB_URI: ${MONGODB_URL}
      SPRING_R2DBC_PASSWORD: 12345678

volumes:
  mysql-data: